text_in_faculty_eng = {
        'GNF': """The policy of the faculty is aimed at developing the directions of the scientific and pedagogical school, actively attracting the teaching staff, graduate students and students to participate in the Federal Target Program competitions, grants from Rosobrnauki, RFBR and oil and gas companies.  It should be noted that the faculty has won four grants from TNK-BP for specialized universities of the Russian Federation.
    The amount of R&D funds is being carried out in full, as well as planned indicators.    The number of monographs and patents has increased 4 times over the past 5 years.  It should be noted that the educational and scientific literature of the department of the faculty is provided both in electronic form and on paper. The updating of part of the educational material is also carried out thanks to the students' production practices and teachers' internships in companies, leading universities and research centers.   Personnel training is conducted in 4 specialties of postgraduate education. There is a joint scientific and pedagogical school at the faculty, which includes all the scientific activities of the SDF.""",
        'TF': """Based on the huge scientific potential, scientists of the faculty conduct fundamental and applied research in various fields of science and technology, actively cooperate and implement their developments at the enterprises of the fuel and energy sector of the country. The scientific developments of the faculty staff are known not only among specialists, but also served as the basis for the design and development of new technologies for oil refining, petrochemistry, biotechnology and the synthesis of new reagents for various industries.
    The main research results are published in journals indexed by Scopus and Web of Science, and in journals recommended by the Higher Attestation Commission. 
    Our scientists take an active part in the work of international congresses and symposiums. Various scientific, technical and methodological conferences are regularly held at the faculty: "Marushkin readings", dedicated to the memory of the famous scientist of the Technological Faculty of USPTU Marushkin B.K., "Industrial safety at explosive and chemically hazardous production facilities", "Industrial safety expertise and diagnostics of hazardous production facilities", "Integration of science and education in the field of bio- and organic chemistry and biotechnology", "Reagent", etc.
    Students and postgraduates of the Faculty of Technology actively participate in the scientific life of the university. Among them are the winners of the "SMART GUY" competition (Ishbaeva A.U., Kazakova A.A., Ibragimov A.A., Davydova O.V., etc.), the "iVolga" forum (Rzayeva Y.R.), grantees of the Russian Foundation for Basic Research (Sunagatullina A.Sh.), the President of the Russian Federation (Raskildina G.Z.), a foreign grant Haldortops A/S program (Shiriyazdanov R.R.), federal target programs (Ishbaeva A.U., Shiriyazdanov R.R.). Many students combine their studies with work in research institutions.""",
        'IT': """Employees and students of the IT Institute take an active part in research activities. The research work of students is an integral part of both the academic and scientific work of the departments of the IT Institute.On the instructions of the heads of the diploma and course design, students prepare literary reviews, make up guidelines, write articles, participate in the project activities of the departments of the Institute. The results of students' work are reported annually at scientific and technical conferences of students, postgraduates and young scientists of USNTU. The works of our students have been repeatedly awarded medals and diplomas of the Ministry of Education of the Russian Federation.
    The Department of Computer Engineering and Engineering Cybernetics is actively engaged in research activities in various fields and industries. Scientific developments are carried out in many thematic areas, from the study of material properties and modeling of technological processes to the development of automated control systems and simulation simulators illustrating various production processes.  
    Information technology Olympiads for students and schoolchildren, various design competitions, as well as the International Scientific and Practical Conference "Information Technologies. Problems and Solutions" (IT'days).
    The main scientific directions of the Department "Automation, Telecommunications and Metrology" are:
- development of methods and software and hardware for obtaining information on quality indicators and technical and economic indicators and decision-making algorithms for the management of oil refining and petrochemical facilities;
    - development of information and control systems for the oil and oil refining industry;
    - research and development of intelligent tools and control systems;
    - development of simulators and simulators for training of technological personnel.""",
        'FTT': """An integral part of the life of students of the Faculty of Pipeline Transport is participation in the cultural and mass life of the university.
    The concept of professional education presupposes the activity and independent activity of students themselves in organizing and conducting events, broad involvement of students to participate in artistic creativity, as well as the use of the positive influence of the most active, purposeful, capable and successful students on their fellow students. One of the strategic objectives of professional education is to increase the number of students involved in cultural, sports and social life.
    Within the framework of this concept, students of the Faculty of Pipeline Transport successfully participate in all intra-university and republican competitions and exhibitions of artistic creativity collectives. Active, cheerful and talented students successfully realize their creative potential for the benefit of the faculty and the university.
    Not a single holiday, not a single competition at USNT takes place without the participation of FTT students.""",
        'ASI': """Outstanding scientists and practitioners Professors A.F. Polak, B.G. Kalimullin, B.V. Goncharov, V.E. Gubin, I.L. Markhasin, V.V. Babkov, I.V. Fedortsev, V.I. Parfenov, L.V. Krotkova made a huge contribution to the formation and development of the Architectural and Construction Institute. They founded and developed promising scientific schools.
    Today, ASI has a scientific school dealing with the problems of synthesis of binding materials, structure formation of cement concretes, corrosion and corrosion protection of reinforced concrete. Leading scientists in this field: Doctors of Technical Sciences V.V. Babkov, V.M. Latypov, A.I. Gabitov, I.V. Nedoseko, V.V. Yakovlev, R.R. Sahibgareev; Candidates of Technical Sciences A.A. Shaimukhametov, A.M. Gaisin, I.G. Terekhov. """,
        'INB': """The Institute of Oil and Gas Business ensures the development of the scientific, educational and innovative potential of USPTU by conducting scientific research and providing scientific and consulting services.
    The purpose of the Research Institute of Oil and Gas Business is to ensure the competitiveness of the results and products of research activities, the competitiveness of students engaged in scientific research and graduate students.
    The Institute of Oil and Gas Business, in cooperation with academic and industry institutes, enterprises of the Republic of Bashkortostan, performs theoretical and applied research on various economic and social topics.
    At the end of 2016, at a meeting of the Government of the Republic of Belarus, priority projects for the strategic development of the Republic of Bashkortostan for the period up to 2030 were approved, which was the logical conclusion of the research work of the interdepartmental group, among whose participants were employees of the Department of Economics and Management at the Oil and Gas Industry Enterprise of the USNTU: Head of the Department Irina Burenina, Professor of the Department Dmitry V. Kotov, Associate Professor of the Department Dilyara Agelamovna Gamilova."""
    }

text_in_faculty_rus = {
        'ГНФ': """Политика факультета направлена на развитие направлений научно-педагогической школы, активное привлечение профессорско-преподавательского состава, аспирантов и студентов к участию в конкурсах ФЦП, грантах Рособрнауки, РФФИ и нефтегазовых компаний.  Следует отметить, что факультетом выиграны четыре гранта компании ТНК-ВР для профильных ВУЗов РФ.
Объем средств по НИОКР выполняется в полном объеме, как и плановые показатели.    Количество монографий и патентов за последние 5 лет выросло в 4 раза.  Следует отметить, что учебной и научной литературой кафедры факультета обеспечены как в электронном виде, так и на бумажных носителях. Обновление части учебного материала производится также благодаря производственным практикам студентов и стажировкам преподавателей в компаниях,  ведущих университетах и научных центрах.   Подготовка кадров ведется по 4 специальностям послевузовского образования. На факультете существует объединенная научно-педагогическая школа, которая включает все научные направления деятельности ГНФ.""",
        'ТФ': """Базируясь на огромном научном потенциале, ученые факультета проводят фундаментальные и прикладные исследования в различных областях науки и техники, активно сотрудничают и внедряют свои разработки на предприятиях ТЭК страны. Научные разработки сотрудников факультета известны не только среди специалистов, но и послужили основой для проектирования и разработки новых технологий процессов переработки нефти, нефтехимии, биотехнологий и синтеза новых реагентов для различных отраслей промышленности.
Основные результаты исследований публикуются в журналах, индексируемых Scopus и Web of Science, и в журналах, рекомендованных ВАК. 
Наши ученые принимают активное участие в работе международных конгрессов и симпозиумов. На факультете регулярно проводятся различные научно-технические и методические конференции: «Марушкинские чтения»,  посвященная памяти известного ученого Технологического факультета УГНТУ Марушкина Б.К., «Промышленная безопасность на взрывопожароопасных и химически опасных производственных объектах», «Экспертиза промышленной безопасности и диагностика опасных производственных объектов», «Интеграция науки и образования в области био- и органической химии и биотехнологии», «Реактив» и др.
Студенты и аспиранты технологического факультета активно участвуют в научной жизни университета. Среди них есть победители конкурса «УМНИК» (Ишбаева А.У., Казакова А.А., Ибрагимов А.А., Давыдова О.В. и др.), форума «iВолга» (Рзаева Ю.Р.), грантополучатели Российского фонда фундаментальных исследований (Сунагатуллина А.Ш.), Президента Российской Федерации (Раскильдина Г.З.), зарубежного гранта HaldorTopsоe A/S programme (Шириязданов Р.Р.), федеральных целевых программ (Ишбаева А.У., Шириязданов Р.Р.). Многие студенты  совмещают учёбу с работой в научно-исследовательских учреждениях.""",
        'IT-институт': """Сотрудники и студенты IT-института принимают активное участие в научно-исследовательской деятельности. Исследовательская работа студентов является неотъемлемой частью как учебной, так и научной работы кафедр IT-института.По заданию руководителей дипломного и курсового проектирования обучающиеся готовят литературные обзоры, составляют методические указания, пишут статьи, участвуют в проектной деятельности кафедр института. Результаты работы студентов ежегодно докладываются на научно-технических конференциях студентов, аспирантов и молодых ученых УГНТУ. Работы наших студентов неоднократно награждались медалями и дипломами Министерства образования Российской Федерации.
Кафедра «Вычислительная техника и инженерная кибернетика» активно занимается научно-исследовательской деятельностью в различных областях и сферах производств. Научные разработки ведутся во многих тематических направлениях от исследования свойств материалов и моделирования технологических процессов до разработки автоматизированных систем управления и имитационных тренажеров, иллюстрирующих различные производственные процессы.  
Ежегодно проводятся олимпиады по информационным технологиям для студентов и школьников, различные конкурсы по проектированию, а также Международная научно-практическая конференция «Информационные технологии. Проблемы и решения» (IT'Days).
Основными научными направлениями кафедры «Автоматизация, телекоммуникация и метрология» являются:
- разработка методов и программно-технических средств получения информации о показателях качества и технико-экономических показателях и алгоритмов принятия решений для управления объектами нефтепереработки и нефтехимии;
- разработка информационно-управляющих систем для нефтяной и нефтеперерабатывающей промышленности;
- исследование и разработка интеллектуальных средств и систем управления;
- разработка имитаторов и тренажеров для обучения технологического персонала.""",
        'ФТТ': """Неотъемлемой частью жизни студентов факультета трубопроводного транспорта является участие в культурно-массовой жизни университета.
Концепция профессионального воспитания предполагает активность и самостоятельную деятельность самих студентов в организации и проведении мероприятий, широкое привлечение студентов к участию в художественном творчестве, а также использование положительного влияния наиболее активных, целеустремленных, способных и успешных студентов на своих сокурсников. Одной из стратегических задач профессионального воспитания является увеличение числа студентов, вовлеченных в культурную, спортивную и общественную жизнь.
В рамках данной концепции студенты факультета трубопроводного транспорта успешно участвуют во всех внутривузовских и республиканских конкурсах и смотрах коллективов художественного творчества. Активные, веселые и талантливые студенты с успехом реализуют свой творческий потенциал во благо факультета и университета.
Ни один праздник, ни один конкурс в УГНТУ не проходит без участия студентов ФТТ.""",
        'АСИ': """В становление и развитие Архитектурно-строительного института огромный вклад внесли выдающиеся ученые и практики профессора А.Ф. Полак, Б.Г. Калимуллин, Б.В. Гончаров, В.Е. Губин, И.Л. Мархасин, В.В. Бабков, И.В. Федорцев, В.И. Парфенов, Л.В. Кроткова. Они основали и развили перспективные научные школы.
Сегодня на АСИ работает научная школа, занимающаяся проблемами синтеза вяжущих материалов, структурообразования цементных бетонов, коррозии и антикоррозионной защиты железобетона. Ведущие ученые в этой области: доктора технических наук В.В. Бабков, В.М. Латыпов, А.И. Габитов, И.В. Недосеко, В.В. Яковлев, Р.Р. Сахибгареев; кандидаты технических наук А.А. Шаймухаметов, А.М. Гайсин, И.Г. Терехов. """,
        'ИНБ': """Институт нефтегазового бизнеса обеспечивает развитие научно-образовательного и инновационного потенциала УГНТУ за счёт проведения научных исследований и оказания научных и консультационных услуг.
Целью НИР Института нефтегазового бизнеса является обеспечение конкурентоспособности результатов и продуктов научно-исследовательской деятельности, конкурентоспособности студентов, занимающихся научными исследованиями и аспирантов.
В Институте нефтегазового бизнеса в содружестве с академическими и отраслевыми институтами, предприятиями Республики Башкортостан выполняются теоретические и прикладные исследования разнообразной экономической  и социальной тематик.
В конце 2016 года на заседании Правительства РБ были утверждены приоритетные проекты стратегического развития Республики Башкортостан на период до 2030 года, что стало логическим завершением научно-исследовательской работы межведомственной группы, среди участников которой были сотрудники кафедры Экономика и управление на предприятии нефтяной и газовой промышленности ФГБОУ ВО УГНТУ: заведующая кафедрой Буренина Ирина Валерьевна, профессор кафедры Котов Дмитрий Валерьевич,  доцент кафедры Гамилова Диляра Агеламовна."""
    }